---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: Billionaires Jet API

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: 117.3.36.11:5000
basePath: /api/v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: User
  - name: Car
  - name: Jet
  - name: Yatch
  - name: Booking
  - name: Profile

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  access-token:
    type: apiKey
    in: header
    name: access-token
  client:
    type: apiKey
    in: header
    name: client
  uid:
    type: apiKey
    in: header
    name: uid
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  user-id:
    name: user-id
    in: path
    description: The user identifier number
    type: integer
    required: true
  tag-name:
    name: tag-name
    in: path
    description: Tag name
    type: string
    required: true

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /auth:
    post:
      tags:
        - Authenticate
      summary: Register with email
      parameters:
        - name: name
          in: formData
          required: true
          type: string
          description: test
        - name: surname
          in: formData
          required: false
          type: string
          description: test
        - name: email
          in: formData
          required: true
          type: string
          description: test
        - name: password
          in: formData
          type: string
          format: password
          description: test
          required: true
        - name: password_confirmation
          in: formData
          type: string
          format: password
          description: test
          required: true
        - name: device[os]
          in: formData
          description: Device os, accepted value are android, ios
        - name: device[token]
          in: formData
          description: Device token
      responses:
        200:
          description: OK
          headers:

          schema:
            type: object
            properties:
              data:
                type: string
    delete:
      tags:
        - Authenticate
      summary: Delete account
      security:
      - access-token: []
        client: []
        uid: []
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                type: string
              _access-token:
                $ref: '#/definitions/AccessToken'
  /auth/sign_in:
    post:
      summary: Sign in
      tags:
        - Authenticate
      description: See the authenticated user's feed.
      parameters:
        - name: email
          in: formData
          description: The email of user
          required: true
          type: string
        - name: password
          in: formData
          description: The password of user
          required: true
          type: string
          format: password
        - name: device[os]
          in: formData
          description: Device os, accepted value are android, ios
        - name: device[token]
          in: formData
          description: Device token
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
              data:
                $ref: '#/definitions/User'
        "401":
          description: Unauthorized
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  example: "Invalid login credentials. Please try again."
  /auth/password:
    post:
      tags:
        - Authenticate
      summary: Reset user password
      hint: Facebook api V2 required both access-token and user-id, url ""
      parameters:
        - name: email
          in: formData
          description: The email of the user
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
              data:
                type: object
  /auth/facebook:
    post:
      tags:
        - Authenticate
      summary: Authenticate via Facebook
      parameters:
        - name: fb_token
          in: formData
          description: The access token
          required: true
          type: string
        - name: fb_user_id
          in: formData
          description: The user_id of facebook
          required: true
          type: string
        - name: device[os]
          in: formData
          description: Device os
        - name: device[token]
          in: formData
          description: Device token
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
              data:
                type: object
  /auth/sign_out:
    delete:
      tags:
        - Authenticate
      summary: Log out
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
        - name: os
          in: formData
          description: Current device os, accepted ios,android
          type: string
        - name: device_token
          in: formData
          description: Current device token
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      name:
        type: string
      surname:
        type: string
      last_sign_in_at:
        type: time
  Attachment:
    type: object
    properties:
      id:
        type: integer
      thumb:
        type: string
      medium:
        type: string
      origin:
        description: Origin avatar url
        type: string
      content_type:
        type: string
