---
swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: Billionaires Jet API

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: 117.3.36.11:5000
basePath: /api/v1
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: User
  - name: Car
  - name: Jet
  - name: Yatch
  - name: Booking
  - name: Profile
  - name: State_and_City

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  access-token:
    type: apiKey
    in: header
    name: access-token
  client:
    type: apiKey
    in: header
    name: client
  uid:
    type: apiKey
    in: header
    name: uid
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  user-id:
    name: user-id
    in: path
    description: The user identifier number
    type: integer
    required: true
  tag-name:
    name: tag-name
    in: path
    description: Tag name
    type: string
    required: true

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /auth:
    post:
      tags:
        - Authenticate
      summary: Register with email
      parameters:
        - name: name
          in: formData
          required: true
          type: string
          description: test
        - name: surname
          in: formData
          required: false
          type: string
          description: test
        - name: email
          in: formData
          required: true
          type: string
          description: test
        - name: organisation
          in: formData
          type: string
        - name: password
          in: formData
          type: string
          format: password
          description: test
          required: true
        - name: password_confirmation
          in: formData
          type: string
          format: password
          description: test
          required: true
        - name: device[os]
          in: formData
          description: Device os, accepted value are android, ios
        - name: device[token]
          in: formData
          description: Device token
      responses:
        200:
          description: OK
          headers:

          schema:
            type: object
            properties:
              data:
                type: string
    delete:
      tags:
        - Authenticate
      summary: Delete account
      security:
      - access-token: []
        client: []
        uid: []
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                type: string
              _access-token:
                $ref: '#/definitions/AccessToken'
  /auth/sign_in:
    post:
      summary: Sign in
      tags:
        - Authenticate
      description: See the authenticated user's feed.
      parameters:
        - name: email
          in: formData
          description: The email of user
          required: true
          type: string
        - name: password
          in: formData
          description: The password of user
          required: true
          type: string
          format: password
        - name: device[os]
          in: formData
          description: Device os, accepted value are android, ios
        - name: device[token]
          in: formData
          description: Device token
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              http_status_code:
                type: integer
              data:
                $ref: '#/definitions/User'
        "401":
          description: Unauthorized
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  example: "Invalid login credentials. Please try again."
  /auth/password:
    post:
      tags:
        - Authenticate
      summary: Reset user password
      hint: Facebook api V2 required both access-token and user-id, url ""
      parameters:
        - name: email
          in: formData
          description: The email of the user
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              http_status_code:
                type: integer
              data:
                type: object
  /api/v1/auth/facebook?omniauth_window_type=inAppBrowser:
    get:
      tags:
        - Authenticate
      summary: Authenticate via Facebook (Using webview)
      description: Using webview to open link, the link should include server url,
        when success checking browser window.data \
        Then using access-token,email, and uid for authenticate via token
      responses:
        200:
          description: Check data object in Webview
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  access-token:
                    type: string
                  client:
                    type: string
                  company_name:
                    type: string
                  email:
                    type: string
                  expiry:
                    type: string
                  full_name:
                    type: string
                  image_url:
                    type: string
                  message:
                    type: string
                  phone:
                    type: string
                  surname:
                    type: string
                  uid:
                    type: string
                  website:
                    type: string
  /api/v1/auth/twitter?omniauth_window_type=inAppBrowser:
    get:
      tags:
        - Authenticate
      summary: Authenticate via Twitter (Using webview)
      description: Using webview to open link, the link should include server url,
        when success checking browser window.data \
        Then using access-token,email, and uid for authenticate via token
      responses:
        200:
          description: Check data object in Webview
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  access-token:
                    type: string
                  client:
                    type: string
                  company_name:
                    type: string
                  email:
                    type: string
                  expiry:
                    type: string
                  full_name:
                    type: string
                  image_url:
                    type: string
                  message:
                    type: string
                  phone:
                    type: string
                  surname:
                    type: string
                  uid:
                    type: string
                  website:
                    type: string
  /auth/facebook:
    post:
      tags:
        - Authenticate
      summary: Authenticate via Facebook
      parameters:
        - name: fb_token
          in: formData
          description: The access token
          required: true
          type: string
        - name: fb_user_id
          in: formData
          description: The user_id of facebook
          required: true
          type: string
        - name: device[os]
          in: formData
          description: Device os
        - name: device[token]
          in: formData
          description: Device token
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              http_status_code:
                type: integer
              data:
                type: object
  /auth/twitter:
    post:
      tags:
        - Authenticate
      summary: Authenticate via Twitter
      parameters:
        - name: tw_token
          in: formData
          description: The access token
          required: true
          type: string
        - name: device[os]
          in: formData
          description: Device os
        - name: device[token]
          in: formData
          description: Device token
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              http_status_code:
                  type: integer
              data:
                type: object
  /auth/sign_out:
    delete:
      tags:
        - Authenticate
      summary: Log out
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
        - name: os
          in: formData
          description: Current device os, accepted ios,android
          type: string
        - name: device_token
          in: formData
          description: Current device token
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
  /profile:
    get:
      tags:
        - Profile
      summary: Profile
      security:
      - access-token: []
        client: []
        uid: []
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
    put:
      tags:
        - Profile
      summary: Update Profile
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
        - name: user[name]
          in: formData
          description: The name of user
          required: true
          type: string
        - name: user[surname]
          in: formData
          description: The surname of user
          type: string
        - name: user[phone]
          in: formData
          description: The phone of user
          type: string
        - name: user[company_name]
          in: formData
          description: The company_name of user
          type: string
        - name: user[organisation]
          in: formData
          description: The organisation of user
          type: string
        - name: user[website]
          in: formData
          description: The website of user
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
  /profile/invitation:
    post:
      tags:
        - Profile
      summary: Send invitation
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
        - name: email
          in: formData
          description: send invitation to this email
          required: true
          type: string
        - name: name
          in: formData
          description: Name of user (optional)
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
  /cars:
    get:
      tags:
        - Car
      summary: listing cars
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
        - name: city_id
          in: path
          description: The id of city
          type: integer
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
              data:
                type: object
                properties:
                  cars:
                    type: array
                    items:
                      $ref: '#/definitions/Car'
  /cars/book:
    post:
      tags:
        - Car
        - Booking
      summary: Booking car
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
        - name: car_id
          in: formData
          required: true
          description: The id of car
          type: integer
        - name: chauffeur
          in: formData
          type: boolean
          description: chauffeur booking
        - name: pick_up_address
          in: formData
          type: string
          description: pick_up_address
        - name: pick_up_lat
          in: formData
          type: string
          description: pick_up_lat
        - name: pick_up_lng
          in: formData
          type: string
          description: pick_up_lng
        - name: destination_address
          in: formData
          type: string
          description: destination_address
        - name: destination_lat
          in: formData
          type: string
          description: destination_lat
        - name: destination_lng
          in: formData
          type: string
          description: destination_lng
        - name: name
          in: formData
          type: string
          description: Customer name
        - name: surname
          in: formData
          type: string
          description: Customer surname
        - name: street_address
          in: formData
          type: string
          description: street address
        - name: city
          in: formData
          type: string
          description: city
        - name: state
          in: formData
          type: string
          description: state
        - name: zip
          in: formData
          type: number
          description: zip
        - name: driver_licence
          in: formData
          type: number
          description: driver_licence
        - name: bithrday
          in: formData
          type: number
          description: bithrday
        - name: state_license_was_issued
          in: formData
          type: number
          description: state_license_was_issued
        - name: insurance_carrier
          in: formData
          type: number
          description: insurance_carrier
        - name: policy
          in: formData
          type: number
          description: policy
        - name: start_date
          in: formData
          type: number
          description: start_date
        - name: end_date
          in: formData
          type: number
          description: end_date
        - name: additional_information
          in: formData
          type: number
          description: additional_information
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
              data:
                type: object
                properties:
                  cars:
                    type: array
                    items:
                      $ref: '#/definitions/CarBooking'
  /states:
    get:
      tags:
        - State_and_City
      summary: listing states and cities
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
              data:
                type: object
                properties:
                  cars:
                    type: array
                    items:
                      $ref: '#/definitions/State'
  /cars/distance_calculate:
    post:
      tags:
        - Car
      summary: calculate distance and duration using google map api
      security:
      - access-token: []
        client: []
        uid: []
      parameters:
        - name: pick_up_address
          in: formData
          required: true
          type: string
        - name: destination_address
          in: formData
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
              http_status_code:
                type: integer
################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      name:
        type: string
      surname:
        type: string
      last_sign_in_at:
        type: time
  Attachment:
    type: object
    properties:
      id:
        type: integer
      thumb:
        type: string
      medium:
        type: string
      origin:
        description: Origin avatar url
        type: string
      content_type:
        type: string
  Car:
    type: object
    properties:
      id:
        type: integer
      brand:
        type: string
      model:
        type: string
      top_speed:
        type: number
      power:
        type: string
      engine:
        type: string
      seats:
        type: integer
      daily_rental_price:
        type: number
      extra_price:
        type: number
      deposit:
        type: number
  CarBooking:
    type: object
    properties:
      id:
        type: integer
      car:
        type: object
        $ref: '#/definitions/Car'
      chauffeur:
        type: boolean
  City:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
  State:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      cities:
        type: array
        items:
          $ref: '#/definitions/City'
